kind: Service
apiVersion: v1
metadata:
  name: spring-boot-hello
spec:
  type: NodePort
  selector:
    app: spring-boot-hello
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
