---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mysql-secrets
spec:
  backendType: secretsManager
  region: us-east-1
  data:
    - key: prod/app/mysql
      name: password
      property: password
