---
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: mysql  
  labels:         
    app: mysql
spec:
  selector:
    matchLabels:        
      app: mysql
  strategy:
    type: Recreate
  template:       
    metadata:
      labels:   
        app: mysql
    spec:                         
      containers:
      - image: mysql:5.6      
        name: mysql
        env:                     
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:              
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        ports:
        - containerPort: 3306          
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql
      volumes:                     
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
